version: "2"
services:
    redis:
        image: "redis:alpine"
        restart: always
        platform: linux/amd64
        container_name: redis
        command: redis-server --requirepass 3ekXG2q72WyfqlFg
        ports:
            - "6379:6379"
    redis-commander:
        image: "rediscommander/redis-commander:latest"
        platform: linux/amd64
        container_name: redis-commander
        restart: always
        environment:
            REDIS_HOSTS: redis
            REDIS_HOST: redis
            REDIS_PORT: redis:6379
            REDIS_PASSWORD: 3ekXG2q72WyfqlFg
            HTTP_USER: admin
            HTTP_PASSWORD: password
        ports:
            - 8081:8081
networks:
    default:
        name: sandbox_network
        external: true